#!/bin/bash

# Use current directory
cd "$(git rev-parse --show-toplevel)" || exit 1

while true; do
    git fetch origin &>/dev/null
    LOCAL=$(git rev-parse HEAD)
    REMOTE=$(git rev-parse origin/$(git symbolic-ref --short HEAD))

    if [ "$LOCAL" != "$REMOTE" ]; then
        echo "Pulling changes..."
        git pull origin HEAD &>> git_pull.log
    else
        echo "No updates available."
    fi

    sleep 1
done   